# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('resources/graphics/attack/attack0.png', 'resources/graphics/attack'),
        ('resources/graphics/attack/attack1.png', 'resources/graphics/attack'),
        ('resources/graphics/attack/attack2.png', 'resources/graphics/attack'),
        ('resources/graphics/attack/attack3.png', 'resources/graphics/attack'),
        ('resources/graphics/attack/attack4.png', 'resources/graphics/attack'),
        ('resources/graphics/backgrounds/end.png', 'resources/graphics/backgrounds'),
        ('resources/graphics/backgrounds/level.jpg', 'resources/graphics/backgrounds'),
        ('resources/graphics/backgrounds/start.png', 'resources/graphics/backgrounds'),
        ('resources/graphics/backgrounds/victory.png', 'resources/graphics/backgrounds'),
        ('resources/graphics/buttons/again.png', 'resources/graphics/buttons'),
        ('resources/graphics/buttons/quit.png', 'resources/graphics/buttons'),
        ('resources/graphics/enemys/death_eaters.png', 'resources/graphics/enemys'),
        ('resources/graphics/enemys/dementor.png', 'resources/graphics/enemys'),
        ('resources/graphics/enemys/hufflepuff.png', 'resources/graphics/enemys'),
        ('resources/graphics/enemys/owl0.png', 'resources/graphics/enemys'),
        ('resources/graphics/enemys/owl1.png', 'resources/graphics/enemys'),
        ('resources/graphics/enemys/owl2.png', 'resources/graphics/enemys'),
        ('resources/graphics/enemys/ravenclaw.png', 'resources/graphics/enemys'),
        ('resources/graphics/enemys/slytherin.png', 'resources/graphics/enemys'),
        ('resources/graphics/explosion/explosion0.png', 'resources/graphics/explosion'),
        ('resources/graphics/explosion/explosion1.png', 'resources/graphics/explosion'),
        ('resources/graphics/explosion/explosion2.png', 'resources/graphics/explosion'),
        ('resources/graphics/explosion/explosion3.png', 'resources/graphics/explosion'),
        ('resources/graphics/explosion/explosion4.png', 'resources/graphics/explosion'),
        ('resources/graphics/explosion/explosion5.png', 'resources/graphics/explosion'),
        ('resources/graphics/explosion/explosion6.png', 'resources/graphics/explosion'),
        ('resources/graphics/explosion/explosion7.png', 'resources/graphics/explosion'),
        ('resources/graphics/explosion/explosion8.png', 'resources/graphics/explosion'),
        ('resources/graphics/explosion/explosion9.png', 'resources/graphics/explosion'),
        ('resources/graphics/explosion/explosion10.png', 'resources/graphics/explosion'),
        ('resources/graphics/explosion/explosion11.png', 'resources/graphics/explosion'),
        ('resources/graphics/misc/buttons.png', 'resources/graphics/misc'),
        ('resources/graphics/misc/hogwarts_logo.png', 'resources/graphics/misc'),
        ('resources/graphics/misc/hp.png', 'resources/graphics/misc'),
        ('resources/graphics/misc/score.png', 'resources/graphics/misc'),
        ('resources/graphics/misc/game_icon.png', 'resources/graphics/misc'),
        ('resources/graphics/harry.png', 'resources/graphics'),
        ('resources/sound/button_sound.wav', 'resources/sound'),
        ('resources/sound/click.wav', 'resources/sound'),
        ('resources/sound/dead.wav', 'resources/sound'),
        ('resources/sound/enemy_dead.wav', 'resources/sound'),
        ('resources/sound/enemy_hit.wav', 'resources/sound'),
        ('resources/sound/main_theme.wav', 'resources/sound'),
        ('resources/sound/shoot.wav', 'resources/sound'),
        ('resources/sound/victory.wav', 'resources/sound'),
        ('resources/fonts/font.ttf', 'resources/fonts'),
    ],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='Порри Гаттер против всех',
    icon='resources/graphics/misc/game_icon.png',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
